export const BioPaxClass = [
	"BindingFeature",
	"BiochemicalPathwayStep",
	"BiochemicalReaction",
	"BioSource",
	"Catalysis",
	"CellularLocationVocabulary",
	"CellVocabulary",
	"ChemicalStructure",
	"Complex",
	"ComplexAssembly",
	"Control",
	"ControlledVocabulary",
	"Conversion",
	"CovalentBindingFeature",
	"Degradation",
	"DeltaG",
	"Dna",
	"DnaReference",
	"DnaRegion",
	"DnaRegionReference",
	"Entity",
	"EntityFeature",
	"EntityReference",
	"EntityReferenceTypeVocabulary",
	"Evidence",
	"EvidenceCodeVocabulary",
	"ExperimentalForm",
	"ExperimentalFormVocabulary",
	"FragmentFeature",
	"Gene",
	"GeneticInteraction",
	"Interaction",
	"InteractionVocabulary",
	"KPrime",
	"ModificationFeature",
	"Modulation",
	"MolecularInteraction",
	"Named",
	"Pathway",
	"PathwayStep",
	"PhenotypeVocabulary",
	"PhysicalEntity",
	"Protein",
	"ProteinReference",
	"Provenance",
	"PublicationXref",
	"RelationshipTypeVocabulary",
	"RelationshipXref",
	"Rna",
	"RnaReference",
	"RnaRegion",
	"RnaRegionReference",
	"Score",
	"SequenceInterval",
	"SequenceLocation",
	"SequenceModificationVocabulary",
	"SequenceRegionVocabulary",
	"SequenceSite",
	"SimplePhysicalEntity",
	"SmallMolecule",
	"SmallMoleculeReference",
	"Stoichiometry",
	"TemplateReaction",
	"TemplateReactionRegulation",
	"TissueVocabulary",
	"Transport",
	"TransportWithBiochemicalReaction",
	"UnificationXref",
	"Xref",
	"XReferrable"
];

export const getDataFormats = [
	{"pc2": "BINARY_SIF", "file_ext": "sif"},
	{"pc2": "BIOPAX", "file_ext": "owl"},
	{"pc2": "EXTENDED_BINARY_SIF", "file_ext": "sif"},
	{"pc2": "GSEA", "file_ext": "gsea"},
	{"pc2": "JSONLD", "file_ext": "json"},
	{"pc2": "SBGN", "file_ext": "sbgn"}
]
